### ISSUE TITLE
Multiple definiton of main() when running make 

### ISSUE THREAD

**Issue by dozadoesit** [MilkJug1/OculusLinkLinux#27]
Running Make I get the following error 

src//USBConnection.o: in function `main':
USBConnection.cc:(.text+0x0): multiple definition of `main'; src//TrackHMD.o:TrackHMD.cc:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:47: oll] Error 1

I fixed they by changing the call in TrackHMD.cc to int main2() instead of int main() and this allowed me to make the project. No clue if this is the right way to fix it but it allowed me to get past the error.

**Comment by MilkJug1** [comment]
Yea this is an issue in the `main` branch of this project, these issues have been fixed in the `cpp` branch, just they haven't been committed to the main branch yet. If I remember correctly, the reason for this issue was I was testing out the Makefile, and I should make a comment on the `Install.md` file that references that this project can't be built at the current moment. I may push the cpp upstream to main for the moment but yea.
